# Generated by Django 4.2.11 on 2024-04-19 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventtag",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="userinterest",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="image",
            field=models.URLField(
                blank=True,
                default="https://www.sjsu.edu/sustainability/pics/cv2building.jpg",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="sjsu_roadmap_image",
            field=models.URLField(
                blank=True,
                default="https://www.cs.sjsu.edu/su/practicalities_files/image002.jpg",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="banner",
            field=models.URLField(
                blank=True,
                default="https://www.sjsu.edu/communications/pics/SpartanSpirit_variation.png",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="club_logo",
            field=models.URLField(
                blank=True,
                default="https://www.sjsu.edu/_images/news/news_prez-seal-communications_010621.jpg",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="members",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pages.major",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name="ClubDepartment",
        ),
        migrations.RemoveField(
            model_name="eventtag",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="userinterest",
            name="tag",
        ),
        migrations.AddField(
            model_name="eventtag",
            name="tag",
            field=models.ManyToManyField(to="pages.tag"),
        ),
        migrations.AddField(
            model_name="userinterest",
            name="tag",
            field=models.ManyToManyField(to="pages.tag"),
        ),
    ]
