# Generated by Django 4.2.11 on 2024-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_eventtag_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinterest",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="userinterest",
            name="user",
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(related_name="events", to="pages.tag"),
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(related_name="users", to="pages.tag"),
        ),
        migrations.DeleteModel(
            name="EventTag",
        ),
        migrations.DeleteModel(
            name="UserInterest",
        ),
    ]
