# Generated by Django 4.2.11 on 2024-05-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_remove_userinterest_tag_remove_userinterest_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="funds",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
