# Generated by Django 4.2.11 on 2024-05-02 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_user_funds"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendance_limit",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
